// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnHglVcH7M4PcKH1lpR6cFyI_allFHbhM',
    appId: '1:584275520806:web:4dbfd48f7956b90ff025e7',
    messagingSenderId: '584275520806',
    projectId: 'enricko-lelang',
    authDomain: 'enricko-lelang.firebaseapp.com',
    storageBucket: 'enricko-lelang.appspot.com',
    measurementId: 'G-TZHYQJZZCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSZRNc2sgT7FjbDmIe3ETWbs1F2iFsu4',
    appId: '1:584275520806:android:6b85bdb53e9e2dfaf025e7',
    messagingSenderId: '584275520806',
    projectId: 'enricko-lelang',
    storageBucket: 'enricko-lelang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwqUK7yyar5G7di0kFazhYucj2GlYcOpU',
    appId: '1:584275520806:ios:e1ec443612503101f025e7',
    messagingSenderId: '584275520806',
    projectId: 'enricko-lelang',
    storageBucket: 'enricko-lelang.appspot.com',
    iosClientId: '584275520806-fts1ff8epb24riv9pun2tmoan2sfif21.apps.googleusercontent.com',
    iosBundleId: 'com.example.tampilanLelangUkkJan292023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwqUK7yyar5G7di0kFazhYucj2GlYcOpU',
    appId: '1:584275520806:ios:e1ec443612503101f025e7',
    messagingSenderId: '584275520806',
    projectId: 'enricko-lelang',
    storageBucket: 'enricko-lelang.appspot.com',
    iosClientId: '584275520806-fts1ff8epb24riv9pun2tmoan2sfif21.apps.googleusercontent.com',
    iosBundleId: 'com.example.tampilanLelangUkkJan292023',
  );
}
